### ISSUE TITLE
Creatures using casterAI behavior incorrect

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1090]
**Description:**
Creatures using casterAI stand in place after being interrupted and don't run to get in melee range or cast another spell. They are also doing this: https://streamable.com/9l9nq (same movement) when interrupted.
When in melee range and not interrupted they melee attack correctly but it seems that their attack timer doesn't pause when they are casting which results in 2 attacks at at time squeezed in between attacks.

rev. 10935

**Comment by zemfi** [comment]
Should also add, the issue has been present since the ptr, another feature is if you oom (no more mana) these caster creatures and never go into melee range, they are forever bolted to the ground, just focusing/targeting you, but never moving. 

You can manipulate them further by going into melee range briefly, do some melee damage then you can kite them, until they can cast there next spell.

**Comment by kelno** [comment]
Fixed
