### ISSUE TITLE
locked at war with 'scryer' even though picking them

### ISSUE THREAD

**Issue by Aurorathe** [thebarrensissues/Issues#1164]
**Description:**
The issue at hand is that i am locked at war with the 'scryer' faction even though i allied my self with them when talking to khadgar. when in shadowmoon valley i was reciving the guard's mark debuff. i did not faction change to alliance.

**Current behaviour:**

I am at war with the 'scryer' so i am unable to interact with any of the npcs and it displays as if i was trying to fight them. In my reputation tab you can see that i am unfriendly with the 'aldor' from the reputation loss when that faction and i am neutral with the 'scryer'

**Expected behaviour:**

I should be not at war with the 'scryer' faction since i picked them to ally myself with so i can interact with the npc's.

**Steps to reproduce the problem:**
1. become allied with scyrers
2. i had not done anyquest for either faction.
3.this may have influenced the being locked into war status with the 'scryer' faction. when i flew over to the scryer town in shadowmoon valley is was still reciving the 'guards mark' debuff and i got attacked by the flying dragonhawks. i did not fight the dragonhawk which attacked me i simply ran away out of combat.
4. at war does not show up for aldor when i display it in the reputation tab.

 **rev. hash/commit:** 	
![WoWScrnShot_042319_151917](https://user-images.githubusercontent.com/49894880/56556472-74015b80-65db-11e9-8e78-3875ef1bdbfa.jpg) (.server info)

![guardsmark](https://user-images.githubusercontent.com/49894880/56556943-b1b2b400-65dc-11e9-8343-665950283d48.jpg)
(getting guards mark)

![drag hawks](https://user-images.githubusercontent.com/49894880/56557284-d22f3e00-65dd-11e9-8e58-6aaabe6628d8.jpg)
(getting attacked by hawks)

**Comment by Harrock1** [comment]
The way I fixed this was to do the khadgar quest then I proceeded to do the [dreadvenom sacs quest](https://www.wowhead.com/quest=10017/strained-supplies) once. This set me to unfriendly with Scryer and Aldor. I then went and did the quest for [dampscale basilisk eyes](https://www.wowhead.com/quest=10024/vorenthals-visions) until I was neutral with Scryer. For me this was 2 times (16 eyes).

What this does is force the game to set you to unfriendly with both scryer and aldor (since space goats start friendly with aldor and belfs start friendly with scryer). When handing in the 2nd quest enough times it successfully set me to neutral for Scryer and unfriendly and at war with Aldor.

**Comment by Cheelout** [comment]
Will deploy SQL Fix tonight.

**Comment by Cheelout** [comment]
FIXED WITH

UPDATE `character_reputation` JOIN `characters`
ON `character_reputation`.`guid`=`characters`.`guid`
SET `character_reputation`.`flags`=80
WHERE `standing`=0 AND `faction`=932 AND `race` IN(1,3,4,7,11) AND `flags` !=80;

UPDATE `character_reputation` JOIN `characters`
ON `character_reputation`.`guid`=`characters`.`guid`
SET `character_reputation`.`flags`=82
WHERE `standing`=0 AND `faction`=934 AND `race` IN(1,3,4,7,11) AND `flags` !=82;

UPDATE `character_reputation` JOIN `characters`
ON `character_reputation`.`guid`=`characters`.`guid`
SET `character_reputation`.`flags`=82
WHERE `standing`=0 AND `faction`=932 AND `race` IN(2,5,6,8,10) AND `flags` !=82;

UPDATE `character_reputation` JOIN `characters`
ON `character_reputation`.`guid`=`characters`.`guid`
SET `character_reputation`.`flags`=80
WHERE `standing`=0 AND `faction`=934 AND `race` IN(2,5,6,8,10) AND `flags` !=80;
