### ISSUE TITLE
Cipher of Damnation

### ISSUE THREAD

**Issue by Davethedruid** [thebarrensissues/Issues#1226]
Cipher of Damnation quest is no longer working.

When boss is summoned he does not become combatable and allies do not land to speak to, cannot initiate fight.

Unable to fight summoned boss as allies and boss despawn before you can interact with boss.

Also, the second fragment part of the pre-requisite quest chain is unable to start due to Ar'tor not giving quest when spoken to.

**Comment by myst56** [comment]
some more info. also having the same problem 

Description:
Cyruhk The Fire Lord kill.

Current behaviour:
Cyrukh the firelord despawns after about 10 seconds and isn't attackable

Expected behaviour:
Cyrukh the firelord should be killable

Steps to reproduce the problem:
-use cipher of damnation to summon Cyruhk
-watch as he despawns seemingly when the flying orcs touch him

Quest ID#10588
Quest NPC- #21181

**Comment by SUN-Leekie** [comment]
Fixed in 11299.
