### ISSUE TITLE
[SSC] - Fathom Lord Karathress - Cataclysmic Bolt - Can Crit when it shouldn't

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1260]
**Description:**

Spell ID: 38441
Cataclysmic Bolt can crit when it should not be able too

**Current behaviour:**

Cataclysmic bolt can crit players, This should not occur

**Expected behaviour:**

Cataclysmic Bolt does not crit (When combined with Beast Within damage, this 1 shots players)

**Steps to reproduce the problem:**

CHANGEME
1. Engage Karathress and kill all his adds
2. Be a mage who gets Cataclysmic Bolted
3. Cry when spell crits for dead

 **rev. hash/commit:** 	

11262

**Comment by giveusmezpls** [comment]
Hi Cheelout, make sure you add relevant labels next time pls.

**Comment by giveusmezpls** [comment]
It makes a lot of sense that this should not be able to crit, i've watched several videos including this one (https://www.youtube.com/watch?v=pub88sW4Jxs) where nobody is one shot even during the Bestial Wrath increased damage.

I would suggest the reason this mechanic exists is to prevent you from just stacking the bosses due to other AoE effects (For example: Frost Bolt).

**Comment by SUN-Leekie** [comment]
Fixed in 11293.
