### ISSUE TITLE
Blazefury medallion scaling should not have been removed

### ISSUE THREAD

**Issue by BrockSamson1** [thebarrensissues/Issues#1267]
**Description:**

Blazefury Medallion does not scale with spellpower. It should scale with spellpower up until the normalisation that comes with all spellpower scaling in 3.0 - WotLK.
Evidence provided of existence of scaling in 2.3.3, evidence existence of fire strike on the normalisation list as well as an exhaustive list of rogue changes compiled from wowhead notes from vanilla to 5.0.0 which does not include scaling changes in TBC.

**Current behaviour:**

Equip blazefury medallion
Pump up spell damage
Note 2 damage on melee strikes

**Expected behaviour:**

Equip blazefury medallion
Pump up spell damage
Note Many damage

**Steps to reproduce the problem:**

CHANGEME
1. Obtain blazefury medallion and equip 
2. Obtain a measure of spell damage
3. Observe 2 damage
 
Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

EVIDENCE -

Exhaustive list of rogue changes from vanilla to 5.0.4 - Note only changes to blazefury medallion are QoL. https://shadowpanther.net/roguechanges.htm

Evidence of scaling into TBC from vanilla -

Blazefury Medallion http://www.wowhead.com/item=17111#comments
By Siralex (3,404 – 12·31) on 2008/02/04 (Patch 2.3.3) 

"I have actually tested this necklace while on a PTR and noticed the fire damage increases by about 50% of your spell damage. I personally was getting 646 regular hits with it and 969 crits (untrinketed). This could possibly be a great item for casters in Arenas."

According to this comment it was still scaling in 2.3.3

Here's evidence that feenix's admin made a conscious decision and did not consider it a bug https://www.bountysource.com/issues/52883184-revert-the-change-to-blazefury-medallion-s-scaling

**Comment by oj449** [comment]
this is a weird one, i was looking into this myself a few weeks back and have found that in vanilla, these items did not in fact scale with spellpower, being blazefury medallion, storm gauntlets, fiery plate gauntlets and fiery retributer.

when tbc came and i think the prepatch as well, they changed how some spell damage to attack things functioned, such as shadowfang, and a by product of these changes was that those items were incorrectly listed as spells as their base, instead of attack based damage, so their damage scaled at the base coefficient of 42.8%, and because hardly anyone picked up on it it went unnoticed throughout tbc to bugfixes, but was found in wotlk.

this is a vanilla video showing storm gauntlets not scaling with spellpower
https://www.youtube.com/watch?v=tDi_g4XDwBU
considering all the items attacks are coded the same way and are named just lightning strike or fire strike, this video proves that at least in vanilla they were not scaling, which would make it weird for them to be scaling come tbc, unless it was an actual bug that went unnoticed during tbc.

**Comment by BrockSamson1** [comment]
Yeah that's the assessment that I understand to be the case. That's in agreement with Feenix's admin conclusion. They noted its existence, but made a conscious decision to rectify the bug regardless. 

I'm asking for that not to be the case. I'm enjoying the spec made from utilising spellpower coefficients, it provides a modest boost to damage and in the interest of player enjoyment and providing widest variety of playstyle and (most importantly to everyone else) being a true to historical recreation of and tribute to the burning crusade in it's heyday.

**Comment by oj449** [comment]
The issue is you can get 2 of the items and scale attack speed and easily hit 6kdps
