### ISSUE TITLE
[Quest] Bloody Vengeance doesn't credit the player correctly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#973]
**Description:**

Quest Bloody Vengeance (10250) doesn't credit the player unless he gets the killing blow. 
During the quest a few NPCs are spawned to aid the player. Unless the player gets the killing blow, though, he does not get credited with the kill and quest isn't marked as complete. There are a few helping NPCs and it's not always easy to get the killing blow.

**Expected behaviour:**

If we tag the quest creature we should get credit no matter who gets the killing blow.

**Steps to reproduce the problem:**

1. .quest add 10250
2. .go xyz -1190.381836 2263.234375 46.398941 (Outland)
3. Use the Horn provided by the quest
4. Observe that you don't get credit.

**rev. hash/commit:** 

Sunstrider rev. 10826 (87ef5fb676f5+)

**Comment by flubbyguty** [comment]
I found that even when getting the killingblow sometimes it would still not give credit. I think it is more related to the nocs doing more damage to him than you (similar to how you do not get quest credit when you finish off a low npc thats fighting another npc). I was able to taunt him, and run far away enough so that I was 1v1ing him and it went through fine.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details!

**Comment by Tamosheik** [comment]
Additional details in #485

**Comment by Jerrythemagicdog** [comment]
Fixed in 11154
